package com.example.ui.theme

import androidx.compose.ui.graphics.Color

val md_theme_light_primary = Color(0xFFB7131A)
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFFDB322F)
val md_theme_light_onPrimaryContainer = Color(0xFFFFFFFF)

val md_theme_light_secondary = Color(0xFF5F5E5E)
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xFFE2DFDE)
val md_theme_light_onSecondaryContainer = Color(0xFF636262)

val md_theme_light_tertiary = Color(0xFF5C5C5C)
val md_theme_light_onTertiary = Color(0xFFFFFFFF)
val md_theme_light_tertiaryContainer = Color(0xFF747474)
val md_theme_light_onTertiaryContainer = Color(0xFFFEFCFC)

val md_theme_light_error = Color(0xFFBA1A1A)
val md_theme_light_errorContainer = Color(0xFFFFDAD6)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_onErrorContainer = Color(0xFF93000A)

val md_theme_light_background = Color(0xFFF9F9F9)
val md_theme_light_onBackground = Color(0xFF1A1C1C)
val md_theme_light_surface = Color(0xFFF9F9F9)
val md_theme_light_onSurface = Color(0xFF1A1C1C)
val md_theme_light_surfaceVariant = Color(0xFFE2E2E2)
val md_theme_light_onSurfaceVariant = Color(0xFF5B403D)
val md_theme_light_outline = Color(0xFF906F6C)
val md_theme_light_inverseOnSurface = Color(0xFFF1F1F1)
val md_theme_light_inverseSurface = Color(0xFF2F3131)
val md_theme_light_inversePrimary = Color(0xFFFFB4AC)
val md_theme_light_shadow = Color(0xFF000000)
val md_theme_light_surfaceTint = Color(0xFFBB171C)
val md_theme_light_outlineVariant = Color(0xFFE4BEB9)
val md_theme_light_scrim = Color(0xFF000000)

val surfaceContainerLowest = Color(0xFFFFFFFF)
val surfaceContainerLow = Color(0xFFF3F3F3)
val surfaceContainer = Color(0xFFEEEEEE)
val surfaceContainerHigh = Color(0xFFE8E8E8)
val surfaceContainerHighest = Color(0xFFE2E2E2)

// Dark theme colors (just mapped to light for now since it's light only mostly)
val md_theme_dark_primary = Color(0xFFFFB4AC)
val md_theme_dark_onPrimary = Color(0xFF690005)
val md_theme_dark_primaryContainer = Color(0xFF93000A)
val md_theme_dark_onPrimaryContainer = Color(0xFFFFDAD6)

val md_theme_dark_secondary = Color(0xFFC8C6C5)
val md_theme_dark_onSecondary = Color(0xFF313030)
val md_theme_dark_secondaryContainer = Color(0xFF474746)
val md_theme_dark_onSecondaryContainer = Color(0xFFE5E2E1)

val md_theme_dark_tertiary = Color(0xFFC7C6C6)
val md_theme_dark_onTertiary = Color(0xFF2E2E2E)
val md_theme_dark_tertiaryContainer = Color(0xFF454545)
val md_theme_dark_onTertiaryContainer = Color(0xFFE3E2E2)

val md_theme_dark_error = Color(0xFFFFB4AB)
val md_theme_dark_errorContainer = Color(0xFF93000A)
val md_theme_dark_onError = Color(0xFF690005)
val md_theme_dark_onErrorContainer = Color(0xFFFFDAD6)

val md_theme_dark_background = Color(0xFF1A1C1C)
val md_theme_dark_onBackground = Color(0xFFE2E2E2)
val md_theme_dark_surface = Color(0xFF1A1C1C)
val md_theme_dark_onSurface = Color(0xFFE2E2E2)
val md_theme_dark_surfaceVariant = Color(0xFF534341)
val md_theme_dark_onSurfaceVariant = Color(0xFFD8C2BF)
val md_theme_dark_outline = Color(0xFFA08C89)
val md_theme_dark_inverseOnSurface = Color(0xFF1A1C1C)
val md_theme_dark_inverseSurface = Color(0xFFE2E2E2)
val md_theme_dark_inversePrimary = Color(0xFFB7131A)
val md_theme_dark_shadow = Color(0xFF000000)
val md_theme_dark_surfaceTint = Color(0xFFFFB4AC)
val md_theme_dark_outlineVariant = Color(0xFF534341)
val md_theme_dark_scrim = Color(0xFF000000)
